name: Push-to-EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            # Definir o diretório do repositório
            REPO_DIR="/home/ec2-user/seu-repositorio"

            # Clonar o repositório se não estiver presente
            if [ ! -d "$REPO_DIR" ]; then
              git clone https://github.com/luixgabriel/brawlhalla-championship-backend.git "$REPO_DIR"
            fi

            # Navegar para o diretório do projeto
            cd "$REPO_DIR"

            # Atualizar o repositório
            git pull origin master

            # Instalar dependências
            npm install

            # Executar migrações do Prisma e gerar o cliente Prisma
            npx prisma migrate deploy
            npx prisma generate
            npm run build

            # Reiniciar o PM2 (certifique-se de que seu aplicativo está configurado no PM2)
            pm2 restart server || pm2 start npm --name "server" -- run start

            # Opcional: salvar a configuração do PM2 para reinicializações
            pm2 save
          EOF
